name: delete

env:
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
  TRACK_DIR: instruqt-tracks
  
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    inputs:
      slug:
        description: Track Slug
        required: true
        type: string
    branches:    
      - '!main'
      - '!master'

jobs:
  PromoteTrack:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Get Track ID
        run: echo "ID=$(TRACKNAME=${{ inputs.slug }} yq eval '.tracks[] | select(.slug == env(TRACKNAME) ) | .id' instruqt-tracks/track-slugs.yml)" >> $GITHUB_ENV

      - name: Delete dev track
        uses: ./.github/actions/track-delete
        with:
          path: ${{ env.TRACK_DIR }}/${{ DEV-inputs.slug }}
